### ISSUE TITLE
Blade Offensive Spin - bg2fixpack and TobEx

### ISSUE THREAD

**Issue by TotoR115** [CamDawg/BG2-Fixpack#10]
There is a bug with the fix for SPCL521 in conjunction with tobex : the additional attack is not granted.

This is due to the following lines 12178:

LPF ADD_SPELL_EFFECT INT_VAR opcode = 1 target = 1 parameter1 = 1 duration = 24 resist_dispel = 2 END // +1 apr

it adds the opcode at the end of effect, after the opcode 206 (protection from spells) which make the +1 APR ineffective.

the use of the following line instead solves the bug :
LPF CLONE_EFFECT INT_VAR silent = 1 check_globals = 0 match_opcode = 65 opcode = 1 target = 1 parameter1 = 1 duration = 24 resist_dispel = 2 END

**Comment by CamDawg** [comment]
Fixed in commit https://github.com/Gibberlings3/BG2-Fixpack/commit/5e79a00d4399c07ab9f68ba54ffceac7bbf2b04d
