### ISSUE TITLE
Fix for Negative Plane Protection's range

### ISSUE THREAD

**Issue by Salk73** [CamDawg/BG2-Fixpack#12]
If I am correct, we need to add line in bold to the list.

// range
ACTION_CLEAR_ARRAY cd_bulk_spell_fixes
ACTION_DEFINE_ASSOCIATIVE_ARRAY cd_bulk_spell_fixes BEGIN

  spdr101 => 90 // chromatic orb (avenger)
  spin104 => 90 // larloch's minor drain (innate)
  spin685 => 60 // magic missile (imoen/promenade cutscene version)
  spin937 => 30 // color spray (mephit innate)
  spin962 => 60 // magic missile (beholder version)
  sppr203 =>  0 // chant
  **sppr413 => 1 // negative plane protection**
  sppr703 => 30 // gate (divine)
  spwi003 => 60 // magic missile (trap wizard version)
  spwi101 => 30 // grease
  spwi103 =>  5 // burning hands
  spwi105 => 30 // color spray (arcane)
  spwi106 => 30 // blindness
  spwi111 => 30 // infravision
  spwi112 => 60 // magic missile (regular wizard version)
  spwi116 => 90 // sleep
  spwi118 => 90 // chromatic orb (arcane)
  spwi119 => 90 // larloch's minor drain (arcane)
  spwi125 => 30 // spook
  spwi313 => 30 // skull trap
  spwi409 => 30 // contagion
  spwi503 => 12 // cone of cold
  spwi905 => 30 // gate (arcane)

**Comment by CamDawg** [comment]
Fixed in commit https://github.com/Gibberlings3/BG2-Fixpack/commit/5e79a00d4399c07ab9f68ba54ffceac7bbf2b04d
