### ISSUE TITLE
Know alignment (arcane version)

### ISSUE THREAD

**Issue by Salk73** [CamDawg/BG2-Fixpack#13]
It seems that the divine version of the Know Alignment spell allows for a saving throw (with a -2 penalty) while the arcane doesn't, even after installing the Fixpack, despite the description clearly mentioning the target able to roll a save vs Spell to resist against it. Neither the arcane nor the divine description mentions the negative modifier for the saving throw.

**Comment by CamDawg** [comment]
This one sucks, as the description itself is inconsistent. I gave it a straight save vs. spell and called it a day. 

Fixed in commit https://github.com/Gibberlings3/BG2-Fixpack/commit/5e79a00d4399c07ab9f68ba54ffceac7bbf2b04d
