### ISSUE TITLE
Boots of lightning speed look like they set the wrong movement rate

### ISSUE THREAD

**Issue by lynxlynxlynx** [CamDawg/BG2-Fixpack#9]
Unlike the boots of speed, which uses haste or a 200% modifier, these just set the rate to 30 (description: double-strength haste). The bg2 default for pcs is 8 or 9*, so that would be 32 or 36. Easiest to just convert it to a 400% mod.

\* I just measured the actual speed and like in bg1, both rates result in the same px/s speed, so I haven't been able to confirm the lore.

**Comment by CamDawg** [comment]
Fixed in commit https://github.com/Gibberlings3/BG2-Fixpack/commit/5e79a00d4399c07ab9f68ba54ffceac7bbf2b04d

Also fixed the handful of effects with timing mode 2 and non-zero durations.
